ProjetoPratico/ProjetoPratico/Controllers/AtividadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetoPratico.Models;

namespace ProjetoPratico.Controllers
{
    public class AtividadesController : Controller
    {
        private BancoEntities db = new BancoEntities();

        // GET: Atividades
        public ActionResult Index()
        {
            return View(db.Atividade.ToList());
        }

        // GET: Atividades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Atividade atividade = db.Atividade.Find(id);
            if (atividade == null)
            {
                return HttpNotFound();
            }
            return View(atividade);
        }

        // GET: Atividades/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Atividades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,descricao,prazo,id_projeto")] Atividade atividade)
        {
            if (ModelState.IsValid)
            {
                db.Atividade.Add(atividade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(atividade);
        }

        // GET: Atividades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Atividade atividade = db.Atividade.Find(id);
            if (atividade == null)
            {
                return HttpNotFound();
            }
            return View(atividade);
        }

        // POST: Atividades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,descricao,prazo,id_projeto")] Atividade atividade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(atividade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(atividade);
        }

        // GET: Atividades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Atividade atividade = db.Atividade.Find(id);
            if (atividade == null)
            {
                return HttpNotFound();
            }
            return View(atividade);
        }

        // POST: Atividades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Atividade atividade = db.Atividade.Find(id);
            db.Atividade.Remove(atividade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetoPratico/ProjetoPratico/Views/Atividades/Adicionar.cshtml
@model ProjetoPratico.Models.Atividade

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Atividade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prazo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prazo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prazo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjetoPratico/ProjetoPratico/Views/Atividades/Create.cshtml
@model ProjetoPratico.Models.Atividade

@{
    ViewBag.Title = "Adicionar";   
}

<h2>Adicionar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Atividade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prazo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prazo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prazo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_projeto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                     var db = new ProjetoPratico.Models.BancoEntities();
                  var projetos = from item in db.Projeto.ToList()
                  select new SelectListItem { Selected = false, Text = item.descricao, Value = item.id.ToString() };
                }
                @Html.DropDownListFor(model => model.id_projeto, projetos, "Selecione", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_projeto)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
                @Html.ActionLink("Voltar", "Index", "Atividades", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoPratico/ProjetoPratico/Views/Atividades/Delete.cshtml
@model ProjetoPratico.Models.Atividade

@{
    ViewBag.Title = "Excluir";    
}

<h2>Excluir</h2>

<h3>Tem certeza de que deseja excluir?</h3>
<div>
    <h4>Atividade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prazo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prazo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_projeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_projeto)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-primary" />
            @Html.ActionLink("Voltar", "Index", "Atividades", new { @class = "btn btn-default" })
        </div>
    }
</div>

ProjetoPratico/ProjetoPratico/Views/Atividades/Details.cshtml
@model ProjetoPratico.Models.Atividade

@{
    ViewBag.Title = "   Detalhes";    
}

<h2>Detalhes</h2>

<div>
    <h4>Atividade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prazo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prazo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_projeto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_projeto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", "Atividades", new { id = Model.id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar", "Index", "Atividades", new { @class = "btn btn-default" })
</p>

ProjetoPratico/ProjetoPratico/Views/Atividades/Edit.cshtml
@model ProjetoPratico.Models.Atividade

@{
    ViewBag.Title = "Editar";    
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Atividade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prazo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prazo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prazo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_projeto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
    var db = new ProjetoPratico.Models.BancoEntities();
    var projetos = from item in db.Projeto.ToList()
                   select new SelectListItem { Selected = false, Text = item.descricao, Value = item.id.ToString() };
                }
                @Html.DropDownListFor(model => model.id_projeto, projetos, "Selecione", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_projeto)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                @Html.ActionLink("Voltar", "Index", "Atividades", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoPratico/ProjetoPratico/Views/Atividades/Editar.cshtml
@model ProjetoPratico.Models.Atividade

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Atividade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prazo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prazo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prazo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjetoPratico/ProjetoPratico/Views/Atividades/Excluir.cshtml
@model ProjetoPratico.Models.Atividade

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Atividade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prazo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prazo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjetoPratico/ProjetoPratico/Views/Atividades/Index.cshtml
@model IEnumerable<ProjetoPratico.Models.Atividade>

@{
    ViewBag.Title = "Atividades";
}

<h2>Atividades</h2>
@{
    var db = new ProjetoPratico.Models.BancoEntities();
    var projeto = "";

}
<p>
    @Html.ActionLink("Adicionar Atividade", "Create", "Atividades", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prazo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.id_projeto)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        projeto = db.Projeto.First(p => p.id == item.id_projeto).descricao;
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prazo)
            </td>
            <td>

                @projeto
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }, new { @class = "btn btn-primary btn-xs" }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.id }, new { @class = "btn btn-info btn-xs" }) |
                @Html.ActionLink("Excluir", "Delete", new { id = item.id }, new { @class = "btn btn-danger btn-xs" })
            </td>
        </tr>
    }

</table>