ProjetoPratico/ProjetoPratico/Controllers/ColaboradoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetoPratico.Models;

namespace ProjetoPratico.Controllers
{
    public class ColaboradoresController : Controller
    {
        private BancoEntities db = new BancoEntities();

        public ActionResult Index()
        {
            if (Session["LoginID"] != null) { return View(db.Colaborador.ToList()); }
            else { return RedirectToAction("Login","Home"); }
            
        }


        public ActionResult Detalhes(int? id)
        {
            if (Session["LoginID"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Colaborador Colaborador = db.Colaborador.Find(id);
                TempData["teste"] = Colaborador.id;
                if (Colaborador == null)
                {
                    return HttpNotFound();
                }
                return View(Colaborador);
            }
            else { return RedirectToAction("Login", "Home"); }
        }


        public ActionResult Adicionar()
        {
            var funcao = new List<SelectListItem> {
              new SelectListItem { Text = "Administrador", Value = "0" },
              new SelectListItem { Text = "Gerente", Value ="1"},
              new SelectListItem { Text = "Moderador", Value ="2"},
              new SelectListItem { Text = "Colaborador", Value ="3"}};
            ViewBag.funcao = funcao;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar([Bind(Include = "id,Nome,cpf,rg,telefone,email,estadoCivil,paginaPessoal,login,senha,ativo,funcao")] Colaborador Colaborador)
        {
            if (ModelState.IsValid)
            {
                db.Colaborador.Add(Colaborador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(Colaborador);
        }


        public ActionResult Editar(int? id)
        {
            var funcao = new List<SelectListItem> {
              new SelectListItem { Text = "Administrador", Value = "0" },
              new SelectListItem { Text = "Gerente", Value ="1"},
              new SelectListItem { Text = "Moderador", Value ="2"},
              new SelectListItem { Text = "Colaborador", Value ="3"}};
            ViewBag.funcao = funcao;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colaborador Colaborador = db.Colaborador.Find(id);
            if (Colaborador == null)
            {
                return HttpNotFound();
            }
            return View(Colaborador);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "id,Nome,cpf,rg,telefone,email,estadoCivil,paginaPessoal,login,senha,ativo,funcao")] Colaborador Colaborador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Colaborador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Colaborador);
        }


        public ActionResult Excluir(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colaborador Colaborador = db.Colaborador.Find(id);
            if (Colaborador == null)
            {
                return HttpNotFound();
            }
            return View(Colaborador);
        }


        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public ActionResult CorfirmarExclusao(int id)
        {
            Colaborador Colaborador = db.Colaborador.Find(id);
            db.Colaborador.Remove(Colaborador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetoPratico/ProjetoPratico/Controllers/EnderecosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetoPratico.Models;

namespace ProjetoPratico.Controllers
{
    public class EnderecosController : Controller
    {
        private BancoEntities db = new BancoEntities();

        // GET: Enderecos
        public ActionResult Index()
        {
            return View(db.Endereco.ToList());
        }

        // GET: Enderecos/Details/5
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Endereco.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // GET: Enderecos/Create
        public ActionResult Adicionar()

        {
            ViewBag.teste = TempData["teste"];
            return View();
        }

        // POST: Enderecos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar([Bind(Include = "Id,logradouro,bairro,numero,complemento,cep,cidade,uf,id_colaborador")] Endereco endereco)
        {
            
            if (ModelState.IsValid)
            {
                db.Endereco.Add(endereco);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(endereco);
        }

        // GET: Enderecos/Edit/5
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Endereco.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // POST: Enderecos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "Id,logradouro,bairro,numero,complemento,cep,cidade,uf,id_colaborador")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                db.Entry(endereco).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(endereco);
        }

        // GET: Enderecos/Delete/5
        public ActionResult Excluir(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Endereco.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // POST: Enderecos/Delete/5
        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmarExclusao(int id)
        {
            Endereco endereco = db.Endereco.Find(id);
            db.Endereco.Remove(endereco);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetoPratico/ProjetoPratico/Views/Colaboradores/Adicionar.cshtml
@model ProjetoPratico.Models.Colaborador

@{
    ViewBag.Title = "Adicionar";
}

<h2>Adicionar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Usuário</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.funcao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.funcao, ProjetoPratico.Models.Funcoes.EnumToSelectListItem<ProjetoPratico.Models.FuncoesEnum>(), "Selecione", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.funcao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estadoCivil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estadoCivil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estadoCivil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paginaPessoal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paginaPessoal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paginaPessoal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.senha, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ativo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
                @Html.ActionLink("Voltar", "Index", "Colaboradores", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoPratico/ProjetoPratico/Views/Colaboradores/Detalhes.cshtml
@model ProjetoPratico.Models.Colaborador

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Colaborador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estadoCivil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estadoCivil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paginaPessoal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paginaPessoal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.login)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ativo)
        </dd>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Editar", "Editar", "Colaboradores", new { id = Model.id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar", "Index", "Colaboradores", new { @class = "btn btn-default" })

    @Html.ActionLink("Adicionar Endereço", "Adicionar", "Enderecos", new { id = Model.id }, new { @class = "btn btn-primary" })
</p>

ProjetoPratico/ProjetoPratico/Views/Colaboradores/Editar.cshtml
@model ProjetoPratico.Models.Colaborador

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Colaborador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        <div class="form-group">
            @Html.LabelFor(model => model.funcao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.funcao, ProjetoPratico.Models.Funcoes.EnumToSelectListItem<ProjetoPratico.Models.FuncoesEnum>(), "Selecione", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.funcao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estadoCivil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estadoCivil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.estadoCivil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paginaPessoal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paginaPessoal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paginaPessoal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.senha, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ativo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                @Html.ActionLink("Voltar", "Index", "Colaboradores", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoPratico/ProjetoPratico/Views/Colaboradores/Excluir.cshtml
@model ProjetoPratico.Models.Colaborador

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Tem certeza de que deseja excluir?</h3>
<div>
    <h4>Colaborador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estadoCivil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estadoCivil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paginaPessoal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paginaPessoal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.login)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-primary" /> 
            @Html.ActionLink("Voltar", "Index", "Colaboradores", new { @class = "btn btn-default" })
        </div>
    }
</div>

ProjetoPratico/ProjetoPratico/Views/Colaboradores/Index.cshtml
@model IEnumerable<ProjetoPratico.Models.Colaborador>

@{
    ViewBag.Title = "Colaboradores";
}

<h2>Usuários cadastrados</h2>

<p>
    @Html.ActionLink("Adicionar Colaborador", "Adicionar", "Colaboradores", new { @class = "btn btn-primary" })
</p>
<table class="table table-striped table-hover table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cpf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.funcao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.login)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ativo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.funcao)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.login)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ativo)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.id }, new{@class = "btn btn-primary btn-xs"})
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.id }, new { @class = "btn btn-info btn-xs" })
                @Html.ActionLink("Excluir", "Excluir", new { id = item.id }, new { @class = "btn btn-danger btn-xs" })
            </td>
        </tr>
    }

</table>