ProjetoPratico/ProjetoPratico/Controllers/ProjetosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetoPratico.Models;

namespace ProjetoPratico.Controllers
{
    public class ProjetosController : Controller
    {
        private BancoEntities db = new BancoEntities();


        public ActionResult Index()
        {
            return View(db.Projeto.ToList());
        }

        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projeto.Find(id);
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto);
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar([Bind(Include = "id,descricao,prazo,observacao,ativo")] Projeto projeto)
        {
            if (ModelState.IsValid)
            {
                db.Projeto.Add(projeto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(projeto);
        }

        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projeto.Find(id);
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "id,descricao,prazo,observacao,ativo")] Projeto projeto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(projeto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(projeto);
        }


        public ActionResult Excluir(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Projeto projeto = db.Projeto.Find(id);
            if (projeto == null)
            {
                return HttpNotFound();
            }
            return View(projeto);
        }


        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmarExclusao(int id)
        {
            Projeto projeto = db.Projeto.Find(id);
            db.Projeto.Remove(projeto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetoPratico/ProjetoPratico/Views/Projetos/Adicionar.cshtml
@model ProjetoPratico.Models.Projeto

@{
    ViewBag.Title = "Adicionar";
}

<h2>Adicionar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Projeto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prazo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prazo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prazo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.observacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ativo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
                @Html.ActionLink("Voltar", "Index", "Projetos", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoPratico/ProjetoPratico/Views/Projetos/Detalhes.cshtml
@model ProjetoPratico.Models.Projeto

@{
    ViewBag.Title = "Detalhes";
    var projeto = "";
}

<h2>Detalhes</h2>

<div>
    <h4>Projeto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prazo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prazo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.observacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ativo)
        </dd>


    </dl>

    <table class="table">
        <tr>
            <th>
               Descrição
            </th>
            <th>
                Prazo
            </th>
            <th>
               Projeto
            </th>
            <th></th>
        </tr>

        @{var db = new ProjetoPratico.Models.BancoEntities();
          var atividades = (from m in db.Atividade
                            where m.id_projeto == Model.id
                            select m).ToList();
        }
        @foreach (var item in atividades)
        {
            projeto = db.Projeto.First(p => p.id == item.id_projeto).descricao;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.prazo)
                </td>
                <td>

                    @projeto
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Detalhes", "Details", new { id = item.id }) |
                    @Html.ActionLink("Excluir", "Delete", new { id = item.id })
                </td>
            </tr>
        }

    </table>

</div>
<p>
    @Html.ActionLink("Editar", "Editar", "Projetos", new { id = Model.id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar", "Index", "Projetos", new { @class = "btn btn-default" })
</p>

ProjetoPratico/ProjetoPratico/Views/Projetos/Editar.cshtml
@model ProjetoPratico.Models.Projeto

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Projeto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prazo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prazo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prazo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.observacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.observacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.observacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ativo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                @Html.ActionLink("Voltar", "Index", "Projetos", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoPratico/ProjetoPratico/Views/Projetos/Excluir.cshtml
@model ProjetoPratico.Models.Projeto

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Tem certeza de que deseja excluir?</h3>
<div>
    <h4>Projeto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prazo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prazo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.observacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-primary" />
           @Html.ActionLink("Voltar", "Index", "Projetos", new { @class = "btn btn-default" })
        </div>
    }
</div>

ProjetoPratico/ProjetoPratico/Views/Projetos/Index.cshtml
@model IEnumerable<ProjetoPratico.Models.Projeto>

@{
    ViewBag.Title = "Projetos";
}

<h2>Projetos</h2>

<p>
    @Html.ActionLink("Adicionar Projeto", "Adicionar", "Projetos", new { @class = "btn btn-primary" })
</p>
<table class="table table-striped table-hover table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prazo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.observacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ativo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prazo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.observacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ativo)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.id }, new { @class = "btn btn-primary btn-xs" }) |
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.id }, new { @class = "btn btn-info btn-xs" }) |
                @Html.ActionLink("Excluir", "Excluir", new { id = item.id }, new { @class = "btn btn-danger btn-xs" })
            </td>
        </tr>
    }

</table>